### ISSUE TITLE
package build process works successfully. but, can not launch(PluginTest.exe)

### ISSUE THREAD

**Issue by codenamexenon** [ErikHedberg/Terminal-Ballistics-Example-Project#1]
also When Launch Profile results : Cook server exited with error code: -1

Do I need to do anything additional settings in how to package?

Env: Unreal Engine Editor 5.2.1, Microsoft Windows 10

DefaultGame.ini added

[/Script/UnrealEd.ProjectPackagingSettings]

+MapsToCook=(FilePath="/Game/FirstPerson/Maps/FirstPersonMap")

**Comment by ErikHedberg** [comment]
Looking into this.

**Comment by Ben-Cykyria** [comment]
Came  here, having the same problem, packaging works fine, starting the packaged build is not possible

Tested (all failed to start exe):

- Launcher 5.2.1, BP only project: Win64 DebugGame / Shipping
- Custom 5.2.1, C++ project: Win64 DebugGame / Shipping, as well as Linux Shipping/DebugBuild

Unfortunately not able to get a core dump either on Windows or Linux, executable just segfaults right away. 

Removing the TB plugin & rebuild solves the problem in all cases/combinations above.

P.S.: Erik, since we had email exchange because of renaming a struct - all tests above were made with the original code from you without modifications.

**Comment by codenamexenon** [comment]
additional info

~~~
AutomationException: Client exited with error code: -2147483645

(see C:\Users\hogehoge\AppData\Local\Temp\T+ue5src+UnrealEngine\Logs\Client.log for more info)
Comment: Client.log Not Found

   at AutomationScripts.Project.RunClient(List`1 DeployContextList, String ClientLogFile, ERunOptions ClientRunFlags, String ClientApp, String ClientCmdLine, ProjectParams Params)
 in %UEWORK%\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\RunProjectCommand.Automation.cs:line 543
if (ClientProcess != null && ClientProcess.ExitCode != 0) {
  throw new AutomationException("Client exited with error code: {0} (see {1} for more info)", ClientProcess.ExitCode, ClientLogFile);
}
~~~

**Comment by ErikHedberg** [comment]
I'm trying to resolve the issue now, it seems like the engine was unable to convert `EObjectTypeQuery::ObjectTypeQuery1` into a collision channel for some reason. (that's the "WorldStatic" collision channel)

**Comment by ErikHedberg** [comment]
A couple other issues came up but are hopefully resolved.
I've bundled this fix in with the struct name changes as well @Ben-Cykyria.
The update is submitted and pending. I'd post a diff here, but it wasn't just a single change.

**Comment by Ben-Cykyria** [comment]
Perfect, thanks a lot! Will see the update in the launcher and get back to you 👍

**Comment by Ben-Cykyria** [comment]
Updated plugin was available already when I posted the comment above, that was quick. 

Results with TB plugin version 1.0.25:

Launcher 5.2.1	
- win64 debug / shipping - OK

Custom engine 5.2.1
- win64 editor - OK 
- win64 debug / shipping - OK 
- linux debug / shipping - OK

As far as I can tell, all issues are resolved 👍

**Comment by ErikHedberg** [comment]
Great to hear!
Made a couple other changes, so there may be another update soon (when epic gets around to approving it) but I'm glad those errors were resolved.

@codenamexenon Let me know if you still encounter these issues. If not, we can close this issue.

**Comment by codenamexenon** [comment]
Results: OK!

UE5 Launcher 5.2.1, Terminal Ballistics plugin version: 1.0.25
 win64 development - OK
thanks. great devs!(@ErikHedberg @Ben-Cykyria)
