### ISSUE TITLE
Bullet Tag: None

### ISSUE THREAD

**Issue by tutmryan** [ErikHedberg/Terminal-Ballistics-Example-Project#11]
Getting Bullet Tag like this result in "None" although already set under `Gameplay Tag`

The code:
![image](https://github.com/user-attachments/assets/d2899928-abd6-4c0c-823f-577d84ae9eeb)

The DA_Bullet:
![image](https://github.com/user-attachments/assets/60638d16-59f6-4ad4-9226-b9ff2db18d70)

**Comment by ErikHedberg** [comment]
Hey, 
looking into this. I'll keep you updated.

**Comment by ErikHedberg** [comment]
@tutmryan This should be fixed in the latest version (v1.0.69), which is currently pending approval.

**Comment by tutmryan** [comment]
Great to hear, thanks @ErikHedberg. I'll keep an eye out when it's up and try out then relay the update / close this issue.

**Comment by tutmryan** [comment]
This issue is resolved, thanks @ErikHedberg !
