### ISSUE TITLE
Invalid ProjectileProperties when trying to add and firing a bullet

### ISSUE THREAD

**Issue by nightails** [ErikHedberg/Terminal-Ballistics-Example-Project#5]
Here is my code for firing a bullet

```
void AWI_WeaponActor::FireBulletProjectile()
{
	if (!BulletData) return;
	
	UTerminalBallisticsSubsystem* TBSubSystem = FTBGetSubsystemHelper::GetTBSubsystem(GetWorld());
	if (!TBSubSystem) return;

	FTBLaunchParams LaunchParams;
	LaunchParams.Owner = Owner;
	LaunchParams.ToIgnore.Add(this);
	LaunchParams.ProjectileSpeed = BulletData->MuzzleVelocity;
	LaunchParams.EffectiveRange = EffectiveRange;
	LaunchParams.FireTransform = WeaponMeshComponent->GetSocketTransform("Muzzle");
	LaunchParams.ObjectTypes = UTerminalBallisticsStatics::GetDefaultObjectTypes();
	LaunchParams.TraceChannel = ECC_GameTraceChannel10;

	FBPOnProjectileComplete OnProjectileComplete;
	FBPOnBulletHit OnBulletHit;
	FBPOnBulletExitHit OnBulletExitHit;
	FBPOnBulletInjure OnBulletInjure;
	
	const FTBProjectileId FiredBulletID = TBSubSystem->AddAndFireBulletWithCallbacks(BulletData, LaunchParams,
		OnProjectileComplete, OnBulletHit, OnBulletExitHit, OnBulletInjure, FTBProjectileId::None, 2);
}
```

No matter which function I tried, I keep getting these error:

```
Warning      LogTerminalBallistics     INVALID_PROJECTILE
Warning      LogTerminalBallistics     INVALID_PROJECTILE
Error        LogTerminalBallistics     Invalid ProjectileProperties
Verbose      LogTerminalBallistics     ZERO_VELOCITY
```

An ID for the bullet is able to generate, but nothing happen the scene.

This is a single player project, so no networking. Help would be very appreciated.

**Comment by nightails** [comment]
Tested with Blueprint, also the same thing. Don't know what I setup wrong, but the example project is running fine. Not my sadly.

**Comment by ErikHedberg** [comment]
Are you passing in one of the preset bullet data assets or a custom/modified one?

**Comment by nightails** [comment]
Preset.

I tried a custom one but also the same result.

**Comment by ErikHedberg** [comment]
Very odd. That would imply the bullet isn't being properly initialized or isn't making it to the simulation task.

What happens when you use a version without the delegates instead?
```cpp
TBSubsystem->AddAndFireBullet(BulletData, LaunchParams, FTBProjectileId::None, 2);
```

By the way, `FTBLaunchParams` has a constructor which fills out most of the defaults for you. (I've tried to provide C++ constructors for almost all of my types)

**Comment by nightails** [comment]
Some update, my current project is still stuck on this problem. But when created a fresh new C++ project and tested it with the first-person template, everything work perfectly.

There maybe some config settings that specific to my project that prevent the plugin from initialize properly. Also notice that all the configs are imported by the engine by default on the new project, where my doesn't setup your config at all and sometime reset after I closed the editor.

I may have to check if I messed with the asset manager somewhere. 😅

**Comment by nightails** [comment]
It is WORKING NOW!!!!!!!

Turnout, I was overriding the `AssetManagerClass` with a custom one for loading `NativeGameplayTags`. Believe I wrote this before the new macros become a thing. Never imagine that it would break plugins. 🤣

Thanks for the help! If you didn't mention that bullet is not being properly initialized, I wouldn't have figured it out.

**Comment by ErikHedberg** [comment]
Huh, never even considered that the tags wouldn't have been loaded. Glad you caught that.
