### ISSUE TITLE
No owner on Add & Fire Node

### ISSUE THREAD

**Issue by BlakeLivSim** [ErikHedberg/Terminal-Ballistics-Example-Project#6]
Updated versions and now the "Add and Fire Bullet with Callbacks node" no longer has an Owner parameter.  Can you advise?

**Comment by ErikHedberg** [comment]
That is correct. The reasoning behind that decision was that since the "LaunchParams" struct already contains an "Owner" member, it was both redundant and potentially confusing to have the owner in both places.

**Comment by BlakeLivSim** [comment]
Okay - THANK YOU for getting back to me so quickly - might want to update your docs when you get a chance.  Without going into huge detail, why does the system need an owner for the projectile? Is it just so you can reference the actor in the event you need functionality? I'm assuming this is the case.  (In my example I was using it for my AI to find the original shooter)

Best,

Blake
________________________________

**Comment by ErikHedberg** [comment]
Internally there isn't much need for the owner, but it is certainly useful knowledge when you want to do stuff with the results. (Like knowing who shot you for example)

**Comment by BlakeLivSim** [comment]
Here is more or less what it says.

VCRUNTIME140
MyProject_Win64_DebugGame!FTBBullet::FTBBullet()
MyProject_Win64_DebugGame!FTBBullet::FTBBullet() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:309]
MyProject_Win64_DebugGame!FTBBullet::CreatePtrFromBulletDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:373]
MyProject_Win64_DebugGame!UTerminalBallisticsSubsystem::CreateBulletSimDataFromDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Subsystems\TerminalBallisticsSubsystem.cpp:437]
MyProject_Win64_DebugGame!UTerminalBallisticsStatics::AddAndFireBulletWithCallbacks() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBStatics.cpp:1575]
MyProject_Win64_DebugGame!UTerminalBallisticsStatics::execAddAndFireBulletWithCallbacks() [d:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Intermediate\Build\Win64\UnrealGame\Inc\TerminalBallistics\UHT\TBStatics.gen.cpp:2

When I pull the trigger, it crashes.  Or when I try to start the project up, it goes non-responsive.  Can you advise on how to proceed.  It fires fine inside the editor, no crashes then.  This happened after I updated to 5.3 and pushed the most recent version of Terminal Balliistcs.  I'm going to try to access the process with VS to debug the packaged game but I have little experience doing that, I'll send you any more information I find.


Blake McCorkle

Engineer/FireMedic

Founder, CEO

RTC www.RunTheCalls.com<http://www.runthecalls.com/> | YouTube Channel<https://www.youtube.com/channel/UCtbS7ZTFKhLhwxcMI_QWL5Q/videos?> | “What is Experience?”<https://youtu.be/-EPUil6gcqE?t=100> | Launch Trailer<https://www.youtube.com/watch?v=08VEg5Ckgfc>



Articles:  "How Long Will It Take For 10 Years Experience?"<https://thelivesimulator.com/how-long-for-10-years%3F> | Pattern Recognition - The Key To Experience<https://www.dropbox.com/s/fh5fvt57layontm/PatternRecognition.pdf?dl=0> | Expense of Experience<https://www.dropbox.com/s/7yta79mhrih0n2o/Expense%20of%20Experience.pdf?dl=0>| Adapt&Overcome - A Brief History of Fire Service<https://www.dropbox.com/s/wu9nkw35en1ldv9/AdaptAndOvercome.pdf?dl=0>| Chaos Thinking<https://www.dropbox.com/s/pnq7zfshxjlr2hr/chaos%20thinking.pdf?dl=0>| Your Users Are Blind - VR Design Principles<https://www.dropbox.com/s/xxctblf54z35ksn/Your%20users%20are%20blind.pdf?dl=0>

[cid:18d7a56b-1118-4051-8781-5cf3f63092c0]

“Run The Calls” VR Training for First Responders, a LIVE Simulator product

**Comment by BlakeLivSim** [comment]
Here is what I found when I set a breakjpoint on "FTBBullet::FTBBullet(const UBulletDataAsset* DataAsset) : DataAsset(DataAsset)"

I'm wondering now if there is a problem with the Data Asset?

Here is the entire crash with the lines the crashlog mentions - Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff VCRUNTIME140 MyProject_Win64_DebugGame!FTBBullet::FTBBullet() MyProject_Win64_DebugGame!FTBBullet::FTBBullet() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:309] MyProject_Win64_DebugGame!FTBBullet::CreatePtrFromBulletDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:373] MyProject_Win64_DebugGame!UTerminalBallisticsSubsystem::CreateBulletSimDataFromDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Subsystems\TerminalBallisticsSubsystem.cpp:437] MyProject_Win64_DebugGame!UTerminalBallisticsStatics::AddAndFireBulletWithCallbacks() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBStatics.cpp:1575] MyProject_Win64_DebugGame!UTerminalBallisticsStatics::execAddAndFireBulletWithCallbacks() [d:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Intermediate\Build\Win64\UnrealGame\Inc\TerminalBallistics\UHT\TBStatics.gen.cpp:242] MyProject_Win64_DebugGame!UObject::execCallMathFunction() MyProject_Win64_DebugGame!UObject::execLet() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!UObject::ProcessContextOpcode() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!UObject::ProcessContextOpcode() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>() MyProject_Win64_DebugGame!ProcessLocalFunction() MyProject_Win64_DebugGame!ProcessLocalScriptFunction() MyProject_Win64_DebugGame!UObject::ProcessInternal() MyProject_Win64_DebugGame!UFunction::Invoke() MyProject_Win64_DebugGame!UObject::ProcessEvent() MyProject_Win64_DebugGame!AActor::ProcessEvent() MyProject_Win64_DebugGame!TScriptDelegate<FNotThreadSafeDelegateMode>::ProcessDelegate<UObject>() MyProject_Win64_DebugGame!FEnhancedInputActionEventDelegateBinding<FEnhancedInputActionHandlerDynamicSignature>::Execute() MyProject_Win64_DebugGame!UEnhancedPlayerInput::EvaluateInputDelegates() MyProject_Win64_DebugGame!UPlayerInput::ProcessInputStack() MyProject_Win64_DebugGame!APlayerController::ProcessPlayerInput() MyProject_Win64_DebugGame!APlayerController::TickPlayerInput() MyProject_Win64_DebugGame!APlayerController::PlayerTick() MyProject_Win64_DebugGame!APlayerController::TickActor() MyProject_Win64_DebugGame!FActorTickFunction::ExecuteTick() MyProject_Win64_DebugGame!FTickFunctionTask::DoTask() MyProject_Win64_DebugGame!TGraphTask<FTickFunctionTask>::ExecuteTask() MyProject_Win64_DebugGame!FNamedTaskThread::ProcessTasksNamedThread() MyProject_Win64_DebugGame!FNamedTaskThread::ProcessTasksUntilQuit() MyProject_Win64_DebugGame!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() MyProject_Win64_DebugGame!FTickTaskSequencer::ReleaseTickGroup() MyProject_Win64_DebugGame!FTickTaskManager::RunTickGroup() MyProject_Win64_DebugGame!UWorld::RunTickGroup() MyProject_Win64_DebugGame!UWorld::Tick() MyProject_Win64_DebugGame!UGameEngine::Tick() MyProject_Win64_DebugGame!FEngineLoop::Tick() MyProject_Win64_DebugGame!GuardedMain() MyProject_Win64_DebugGame!GuardedMainWrapper() MyProject_Win64_DebugGame!LaunchWindowsStartup() MyProject_Win64_DebugGame!WinMain() MyProject_Win64_DebugGame!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288] kernel32 ntdll

[cid:09fb1c60-8f3d-4f25-8d49-37816ae30e15]
________________________________
From: Blake McCorkle
Sent: Monday, June 10, 2024 1:11 PM
To: ErikHedberg/Terminal-Ballistics-Example-Project ***@***.***>
Subject: Crash when firing gun in Terminal ballistics, PACKAGED DEBUG BUILD ONLY.

Here is more or less what it says.

VCRUNTIME140
MyProject_Win64_DebugGame!FTBBullet::FTBBullet()
MyProject_Win64_DebugGame!FTBBullet::FTBBullet() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:309]
MyProject_Win64_DebugGame!FTBBullet::CreatePtrFromBulletDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBBullets.cpp:373]
MyProject_Win64_DebugGame!UTerminalBallisticsSubsystem::CreateBulletSimDataFromDataAsset() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Subsystems\TerminalBallisticsSubsystem.cpp:437]
MyProject_Win64_DebugGame!UTerminalBallisticsStatics::AddAndFireBulletWithCallbacks() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Core\TBStatics.cpp:1575]
MyProject_Win64_DebugGame!UTerminalBallisticsStatics::execAddAndFireBulletWithCallbacks() [d:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\TerminalBallistics\Intermediate\Build\Win64\UnrealGame\Inc\TerminalBallistics\UHT\TBStatics.gen.cpp:2

When I pull the trigger, it crashes.  Or when I try to start the project up, it goes non-responsive.  Can you advise on how to proceed.  It fires fine inside the editor, no crashes then.  This happened after I updated to 5.3 and pushed the most recent version of Terminal Balliistcs.  I'm going to try to access the process with VS to debug the packaged game but I have little experience doing that, I'll send you any more information I find.


Blake McCorkle

Engineer/FireMedic

Founder, CEO

RTC www.RunTheCalls.com<http://www.runthecalls.com/> | YouTube Channel<https://www.youtube.com/channel/UCtbS7ZTFKhLhwxcMI_QWL5Q/videos?> | “What is Experience?”<https://youtu.be/-EPUil6gcqE?t=100> | Launch Trailer<https://www.youtube.com/watch?v=08VEg5Ckgfc>



Articles:  "How Long Will It Take For 10 Years Experience?"<https://thelivesimulator.com/how-long-for-10-years%3F> | Pattern Recognition - The Key To Experience<https://www.dropbox.com/s/fh5fvt57layontm/PatternRecognition.pdf?dl=0> | Expense of Experience<https://www.dropbox.com/s/7yta79mhrih0n2o/Expense%20of%20Experience.pdf?dl=0>| Adapt&Overcome - A Brief History of Fire Service<https://www.dropbox.com/s/wu9nkw35en1ldv9/AdaptAndOvercome.pdf?dl=0>| Chaos Thinking<https://www.dropbox.com/s/pnq7zfshxjlr2hr/chaos%20thinking.pdf?dl=0>| Your Users Are Blind - VR Design Principles<https://www.dropbox.com/s/xxctblf54z35ksn/Your%20users%20are%20blind.pdf?dl=0>

[cid:18d7a56b-1118-4051-8781-5cf3f63092c0]

“Run The Calls” VR Training for First Responders, a LIVE Simulator product
