### ISSUE TITLE
Calling UTerminalBallisticsStatics::AddAndFireTestBullet causes crash

### ISSUE THREAD

**Issue by Eqric** [ErikHedberg/Terminal-Ballistics-Example-Project#8]
Hello!
When I call AddAndFireTestBullet I get a crash due to SimData.World and SimData.TerminalBallisticsSubsystem being nullptr.

I solved it by adding 
`SimData.World = World;
SimData.TerminalBallisticsSubsystem = TBSubsystem;`
on line 1898 in TBStatics.cpp

**Comment by ErikHedberg** [comment]
Hey,
thanks for finding this as well as a solution.
I'll be sure to fix this and get an update out as soon as possible!
