### ISSUE TITLE
Crash in TerminalBallisticsProjectileThread.cpp#667

### ISSUE THREAD

**Issue by maschere** [ErikHedberg/Terminal-Ballistics-Example-Project#9]
I'm seeing several crash reports from players for my game, that lead back to line 667 in TerminalBallisticsProjectileThread.cpp "std::unique_lock<std::mutex> lock(TaskMutex);" . It seems to always happen on game start. I cannot reproduce it on my end unfortunately. Here is the stack trace of one player.

```
msvcp140!mtx_do_lock line 103 in d:\a01\_work\2\s\src\vctools\crt\github\stl\src\mutex.cpp

JoyOfProgramming_Win64_Shipping!std::_Mutex_base::lock line 52 in C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\INCLUDE\mutex

JoyOfProgramming_Win64_Shipping!std::unique_lock<std::mutex>::{ctor} line 144 in C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\INCLUDE\mutex

JoyOfProgramming_Win64_Shipping!FTBProjectileWorkerThread::Run line 667 in F:\gamedev\ue5_ipc\Plugins\TerminalBallistics\Source\TerminalBallistics\Private\Threading\TerminalBallisticsProjectileThread.cpp
```

Any ideas what might be causing this?

**Comment by maschere** [comment]
I think, this might be related https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio ?

**Comment by ErikHedberg** [comment]
Huh, very interesting. The article you found does indeed look like it captures the problem, especially since my development environment is using an earlier version of the `mutex` header than the one in the stack trace you posted.

I'll likely follow the advice of the Microsoft developers given in their changelog related to this issue and define `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`
If you would like to try that out, you can add this to the "TerminalBallistics.build.cs" file:
```c#
PublicDefinitions.Add("_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR=1");
```

**Comment by maschere** [comment]
I can confirm that installing the newest VC++ 2022 Redistributable fixes the issue (as outlined in the linked Microsoft article) for the affected players. Adding that flag should however fix it for all players, whether they have the newest redist installed or not, right? I will include this in my next patch and report back.

**Comment by ErikHedberg** [comment]
Yes that is the hope. I do appreciate your willingness to test this as well, so thank you.

**Comment by maschere** [comment]
Adding the flag fixes the issue as far as I can tell - it does not show up in my crash reports anymore 
 since the last update.
